// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using gbH60Services.Model;

#nullable disable

namespace gbH60Services.Migrations
{
    [DbContext(typeof(H60assignment2DbGbContext))]
    partial class H60assignment2DbGbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("gbH60Services.Model.CartItem", b =>
                {
                    b.Property<int>("CartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartItemId"));

                    b.Property<int?>("CartId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(8,2)");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("CartItemId");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("gbH60Services.Model.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("CreditCard")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            CreditCard = "1111222233334444",
                            Email = "john-doe@email.com",
                            FirstName = "John",
                            LastName = "Doe",
                            PhoneNumber = "1234567890",
                            Province = "ON"
                        },
                        new
                        {
                            CustomerId = 2,
                            CreditCard = "1111222233334444",
                            Email = "jane-doe@email.com",
                            FirstName = "Jane",
                            LastName = "Doe",
                            PhoneNumber = "1234567890",
                            Province = "QC"
                        });
                });

            modelBuilder.Entity("gbH60Services.Model.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateFulfilled")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Taxes")
                        .HasColumnType("numeric(8, 2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric(10, 2)");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("gbH60Services.Model.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemId"));

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(8, 2)");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderItemId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("gbH60Services.Model.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProductID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<decimal?>("BuyPrice")
                        .HasColumnType("numeric(8, 2)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ImageURL")
                        .HasMaxLength(2083)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2083)");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("ProdCatId")
                        .HasColumnType("int");

                    b.Property<decimal?>("SellPrice")
                        .HasColumnType("numeric(8, 2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex(new[] { "ProdCatId" }, "IX_Product_ProdCatId");

                    b.ToTable("Product", (string)null);

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            BuyPrice = 250m,
                            Description = "This is the classic batmobile from Tim Burton's 1989 Batman, as a kid's car.",
                            ImageURL = "https://i.imgur.com/uOoAU3k.png",
                            Manufacturer = "GBC",
                            Name = "1989 Batmobile",
                            ProdCatId = 1,
                            SellPrice = 300m,
                            Stock = 10
                        },
                        new
                        {
                            ProductId = 2,
                            BuyPrice = 300m,
                            Description = "This is the classic batmobile from Batman: The Animated Series, as a kid's car.",
                            Manufacturer = "GBC",
                            Name = "Batman: The Animated Series Batmobile",
                            ProdCatId = 1,
                            SellPrice = 350m,
                            Stock = 5
                        },
                        new
                        {
                            ProductId = 3,
                            BuyPrice = 200m,
                            Description = "This is the batmobile from Christopher Nolan's Dark Knight Trilogy, as a kid's car.",
                            ImageURL = "https://i.imgur.com/DDVv15J.png",
                            Manufacturer = "GBC",
                            Name = "The Tumbler",
                            ProdCatId = 1,
                            SellPrice = 250m,
                            Stock = 15
                        },
                        new
                        {
                            ProductId = 4,
                            BuyPrice = 150m,
                            Description = "This is the batmobile from Matt Reeves' 2022 The Batman, as a kid's car.",
                            Manufacturer = "GBC",
                            Name = "The Batman (2022) Batmobile",
                            ProdCatId = 1,
                            SellPrice = 200m,
                            Stock = 15
                        },
                        new
                        {
                            ProductId = 5,
                            BuyPrice = 10m,
                            Description = "This is a shirt with the Bat-Symbol on it.",
                            ImageURL = "https://i.imgur.com/CdlTueC.png",
                            Manufacturer = "GBC",
                            Name = "Bat-Symbol Shirt",
                            ProdCatId = 2,
                            SellPrice = 15m,
                            Stock = 20
                        },
                        new
                        {
                            ProductId = 6,
                            BuyPrice = 15m,
                            Description = "This is a shirt with The Joker on it.",
                            ImageURL = "https://i.imgur.com/KnHLQZk.png",
                            Manufacturer = "GBC",
                            Name = "Joker Shirt",
                            ProdCatId = 2,
                            SellPrice = 20m,
                            Stock = 20
                        },
                        new
                        {
                            ProductId = 7,
                            BuyPrice = 20m,
                            Description = "This is a shirt with Harley Quinn on it.",
                            Manufacturer = "Andriu",
                            Name = "Harley Quinn Shirt",
                            ProdCatId = 2,
                            SellPrice = 25m,
                            Stock = 20
                        },
                        new
                        {
                            ProductId = 8,
                            BuyPrice = 15m,
                            Description = "This is a shirt with Scarecrow on it.",
                            Manufacturer = "GBC",
                            Name = "Scarecrow Shirt",
                            ProdCatId = 2,
                            SellPrice = 20m,
                            Stock = 20
                        },
                        new
                        {
                            ProductId = 9,
                            BuyPrice = 5m,
                            Description = "This is a steel replica of a Batarang. This is made for display and should not be thrown or used as a weapon.",
                            ImageURL = "https://i.imgur.com/y3g2oOE.png",
                            Manufacturer = "GBC",
                            Name = "Batarang",
                            ProdCatId = 3,
                            SellPrice = 10m,
                            Stock = 5
                        },
                        new
                        {
                            ProductId = 10,
                            BuyPrice = 15m,
                            Description = "This is an aluminum replica of Riddler's Staff. This is made for display and should not be used as a weapon.",
                            ImageURL = "https://i.imgur.com/GO1qH0z.png",
                            Manufacturer = "GBC",
                            Name = "Riddler's Staff",
                            ProdCatId = 3,
                            SellPrice = 20m,
                            Stock = 15
                        },
                        new
                        {
                            ProductId = 11,
                            BuyPrice = 5m,
                            Description = "This is a modern take on Batman's Shark Repellent from the 1966 Batman movie. This is made for display and should not be used to repel sharks or any other creatures.",
                            ImageURL = "https://i.imgur.com/v3fZC0J.png",
                            Manufacturer = "GBC",
                            Name = "Shark Repellent",
                            ProdCatId = 3,
                            SellPrice = 10m,
                            Stock = 20
                        },
                        new
                        {
                            ProductId = 12,
                            BuyPrice = 10m,
                            Description = "This is a steel replica of The Joker's Playing Card weapons. This is made for display and should not be thrown or used as a weapon.",
                            ImageURL = "https://i.imgur.com/U9uKlWf.png",
                            Manufacturer = "GBC",
                            Name = "Joker's Playing Cards",
                            ProdCatId = 3,
                            SellPrice = 15m,
                            Stock = 5
                        },
                        new
                        {
                            ProductId = 13,
                            BuyPrice = 40m,
                            Description = "This is a high quality figure of Frank Miller's Dark Knight.",
                            ImageURL = "https://www.tftoys.ca/cdn/shop/products/McFarlaneDCMultiverseDarkKnightReturnsBatman3_large.jpg?v=1634916529",
                            Manufacturer = "McFarlane Toys",
                            Name = "Frank Miller's Dark Knight Figure",
                            ProdCatId = 4,
                            SellPrice = 45m,
                            Stock = 15
                        },
                        new
                        {
                            ProductId = 14,
                            BuyPrice = 300m,
                            Description = "This is a high quality figure of The Joker from Tim Burton's 1989 Batman movie.",
                            ImageURL = "https://i.pinimg.com/474x/d0/0f/fe/d00ffeb2ef5c53614261c97d59475916.jpg",
                            Manufacturer = "Hot Toys",
                            Name = "The Joker (1989 Version) DX Series Figure",
                            ProdCatId = 4,
                            SellPrice = 310m,
                            Stock = 2
                        },
                        new
                        {
                            ProductId = 15,
                            BuyPrice = 100m,
                            Description = "This is a high quality figure of Harley Quinn from the game, Batman: Arkham Knight.",
                            ImageURL = "https://m.media-amazon.com/images/I/71oyx1LdP+L._AC_UF894,1000_QL80_.jpg",
                            Manufacturer = "Mattel",
                            Name = "Arkham Knight Harley Quinn Figure",
                            ProdCatId = 4,
                            SellPrice = 105m,
                            Stock = 0
                        },
                        new
                        {
                            ProductId = 16,
                            BuyPrice = 150m,
                            Description = "This is a high quality figure of Poison Ivy from the comic, Batman: Hush.",
                            ImageURL = "https://i.ebayimg.com/images/g/MjgAAOSwK~pjrWuq/s-l1200.jpg",
                            Manufacturer = "Medicom",
                            Name = "Batman: Hush Poison Ivy Figure",
                            ProdCatId = 4,
                            SellPrice = 160m,
                            Stock = 1
                        },
                        new
                        {
                            ProductId = 17,
                            BuyPrice = 25m,
                            Description = "This is Frank Miller's infamous graphic novel, The Dark Knight Returns.",
                            ImageURL = "https://static.wikia.nocookie.net/batman",
                            Manufacturer = "Frank Miller",
                            Name = "The Dark Knight Returns",
                            ProdCatId = 5,
                            SellPrice = 30m,
                            Stock = 5
                        },
                        new
                        {
                            ProductId = 18,
                            BuyPrice = 25m,
                            Description = "In a world where Joker becomes sane and sues Batman for his senseless violence against the mentally ill.",
                            ImageURL = "https://static.dc.com/dc/files/default_images/BMJKWK_01_300-001_HD_5b7f187f0c3930.50204153.jpg",
                            Manufacturer = "Sean Murphy",
                            Name = "Batman: White Knight",
                            ProdCatId = 5,
                            SellPrice = 30m,
                            Stock = 4
                        },
                        new
                        {
                            ProductId = 19,
                            BuyPrice = 50m,
                            Description = "A comic that takes place during Bruce's first year as Batman. Will he be able to save Gotham?",
                            ImageURL = "https://cdn2.penguin.com.au/covers/original/9781401207526.jpg",
                            Manufacturer = "Frank Miller and David Mazzucchelli",
                            Name = "Batman: Year One",
                            ProdCatId = 5,
                            SellPrice = 55m,
                            Stock = 7
                        },
                        new
                        {
                            ProductId = 20,
                            BuyPrice = 20m,
                            Description = "A comic that explores the possible origins of The Joker, as well as a thrilling modern day story with The Clown Prince of Crime.",
                            ImageURL = "https://static.wikia.nocookie.net/marvel_dc/images/1/17/Batman_The_Killing_Joke.jpg",
                            Manufacturer = "Alan Moore",
                            Name = "Batman: The Killing Joke",
                            ProdCatId = 5,
                            SellPrice = 25m,
                            Stock = 10
                        });
                });

            modelBuilder.Entity("gbH60Services.Model.ProductCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CategoryID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("ImageURL")
                        .HasMaxLength(2083)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2083)");

                    b.Property<string>("ProdCat")
                        .IsRequired()
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)");

                    b.HasKey("CategoryId");

                    b.ToTable("ProductCategory", (string)null);

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            ImageURL = "https://www.iconpacks.net/icons/2/free-car-icon-2897-thumb.png",
                            ProdCat = "Kid's Ride-On Cars"
                        },
                        new
                        {
                            CategoryId = 2,
                            ImageURL = "https://cdn-icons-png.flaticon.com/512/3210/3210104.png",
                            ProdCat = "T-Shirts"
                        },
                        new
                        {
                            CategoryId = 3,
                            ImageURL = "https://cdn-icons-png.flaticon.com/512/4905/4905617.png",
                            ProdCat = "Props/Replicas"
                        },
                        new
                        {
                            CategoryId = 4,
                            ImageURL = "https://cdn-icons-png.flaticon.com/512/6967/6967649.png",
                            ProdCat = "Figures"
                        },
                        new
                        {
                            CategoryId = 5,
                            ImageURL = "https://cdn-icons-png.flaticon.com/512/29/29302.png",
                            ProdCat = "Comics/Graphic Novels"
                        });
                });

            modelBuilder.Entity("gbH60Services.Model.ShoppingCart", b =>
                {
                    b.Property<int>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartId"));

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.HasKey("CartId");

                    b.HasIndex("CustomerId")
                        .IsUnique()
                        .HasFilter("[CustomerId] IS NOT NULL");

                    b.ToTable("ShoppingCarts");
                });

            modelBuilder.Entity("gbH60Services.Model.CartItem", b =>
                {
                    b.HasOne("gbH60Services.Model.ShoppingCart", "ShoppingCart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId");

                    b.HasOne("gbH60Services.Model.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId");

                    b.Navigation("Product");

                    b.Navigation("ShoppingCart");
                });

            modelBuilder.Entity("gbH60Services.Model.Order", b =>
                {
                    b.HasOne("gbH60Services.Model.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("gbH60Services.Model.OrderItem", b =>
                {
                    b.HasOne("gbH60Services.Model.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId");

                    b.HasOne("gbH60Services.Model.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("gbH60Services.Model.Product", b =>
                {
                    b.HasOne("gbH60Services.Model.ProductCategory", "ProdCat")
                        .WithMany("Products")
                        .HasForeignKey("ProdCatId")
                        .IsRequired()
                        .HasConstraintName("FK_Product_ProductCategory");

                    b.Navigation("ProdCat");
                });

            modelBuilder.Entity("gbH60Services.Model.ShoppingCart", b =>
                {
                    b.HasOne("gbH60Services.Model.Customer", "Customer")
                        .WithOne("ShopCart")
                        .HasForeignKey("gbH60Services.Model.ShoppingCart", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("gbH60Services.Model.Customer", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("ShopCart");
                });

            modelBuilder.Entity("gbH60Services.Model.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("gbH60Services.Model.Product", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("gbH60Services.Model.ProductCategory", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("gbH60Services.Model.ShoppingCart", b =>
                {
                    b.Navigation("CartItems");
                });
#pragma warning restore 612, 618
        }
    }
}
